#undef MyPVNodeSMP
#undef OppPVNodeSMP
#undef MyAllSMP
#undef OppAllSMP
#undef MyCutSMP
#undef OppCutSMP
#undef MyMultiPV
#undef MyPVQsearch
#undef MyPVQsearchCheck
#undef MyQsearch
#undef MyQsearchCheck
#undef MyLowDepth
#undef MyLowDepthCheck
#undef MyExclude
#undef MyExcludeCheck
#undef MyCut
#undef MyCutCheck
#undef MyAll
#undef MyAllCheck
#undef MyPV
#undef MyRootNode
#undef MyAnalysis
#undef MyTop
#undef MyTopAnalysis
#undef MyAttacked
#undef OppAttacked
#undef MyAttackedPawns
#undef OppAttackedPawns
#undef OppPVQsearch
#undef OppPVQsearchCheck
#undef OppQsearch
#undef OppQsearchCheck
#undef OppLowDepth
#undef OppLowDepthCheck
#undef OppExclude
#undef OppExcludeCheck
#undef OppCut
#undef OppCutCheck
#undef OppAll
#undef OppAllCheck
#undef OppPV
#undef OppRootNode
#undef OppAnalysis
#undef OppTop
#undef OppTopAnalysis
#undef OppOccupied
#undef BitboardOppP
#undef BitboardOppN
#undef BitboardOppBL
#undef BitboardOppBD
#undef BitboardOppR
#undef BitboardOppQ
#undef BitboardOppK
#undef MyOccupied
#undef BitboardMyP
#undef BitboardMyN
#undef BitboardMyBL
#undef BitboardMyBD
#undef BitboardMyR
#undef BitboardMyQ
#undef BitboardMyK
#undef MyKingSq
#undef OppKingSq
#undef EnumOppP
#undef EnumOppN
#undef EnumOppBL
#undef EnumOppBD
#undef EnumOppR
#undef EnumOppQ
#undef EnumOppK
#undef EnumMyP
#undef EnumMyN
#undef EnumMyBL
#undef EnumMyBD
#undef EnumMyR
#undef EnumMyQ
#undef EnumMyK
#undef OppKingCheck
#undef MyCapture
#undef MyOrdinary
#undef MyPositionalGain
#undef MyEvasion
#undef MyQuietChecks
#undef MySEE
#undef Make
#undef Undo
#undef IllegalMove
#undef MoveIsCheck
#undef MyOK
#undef MyNext
#undef MyNull
#undef SixthRank
#undef FourthRank
#undef FourthRankBitboard
#undef IsPassedPawn
#undef MyXray
#undef OppXray
#undef MyXrayTable
#undef OppXrayTable
#undef MyKingCheck
#undef MyCount
#undef MyCountEvasions
#undef ImInCheck
#undef EighthRank
#undef CaptureRight
#undef FromLeft
#undef CaptureLeft
#undef FromRight
#undef Forward
#undef ForwardLeft
#undef ForwardRight
#undef Backward
#undef ForwardShift
#undef BackShift
#undef SeventhRank
#undef BackShift2
#undef Forward2
#undef SecondRank
#undef SecondSixthRanks
#undef OnThirdRank
#undef SecondSixthRanks
#undef BitboardSeventhRank
#undef BitboardEighthRank
#undef WhiteA7
#undef WhiteH7
#undef CaptureEP
#undef PromQueenCap
#undef PromKnightCap
#undef CastleOO
#undef CastleOOO
#undef WhiteF1G1
#undef WhiteC1D1
#undef WhiteB1C1D1
#undef WhiteE1
#undef WhiteC1
#undef WhiteG1
#undef UnderProm
#undef OnSecondRank
#undef CanCaptureRight
#undef CanCaptureLeft
#undef PawnGuard
#undef FourthEighthRankNoH
#undef FourthEighthRankNoA
#undef BackRight
#undef BackRight2
#undef BackRight3
#undef BackLeft
#undef BackLeft2
#undef BackLeft3
#undef NumberRank5
#undef NumberRank2
#undef PieceIsMine
#undef PieceIsOpp
#undef Backward2
#undef PieceIsOppPawn
